### ISSUE TITLE
Format and create word document

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/SOEN342_TeamB#7]
Formatting and creating the word doc with our comparative study (Part 1) and product presentation (part 2). Review the document as well and bring up any suggestions/modifications if needed

**Comment by Arsollo** [comment]
Report mostly finalized, it just needs a bit of formatting in order to make all its sections coherent, having the same style

**Comment by imran1289-ah** [comment]
i formatted to make it in order and made it coherent, u guys can see if it is good

**Comment by imran1289-ah** [comment]
Document submitted to moodle along with the github link
