### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by imran1289-ah** [imran1289-ah/SOEN342_TeamB#9]
One of our elicitations techniques will be to do a survey to get the users needs.

**Comment by Arsollo** [comment]
@sFranchetto already created a google form which he sent out on multiple servers on discord. Once we collect enough data, I will go ahead and perform the analysis and add it to the report.

**Comment by sFranchetto** [comment]
Survey closed. 
Took results from September 29th @ 7:30 AM to September 30th @ 12:30PM. There were 47 responses to our survey.

[Our survey](https://docs.google.com/forms/d/e/1FAIpQLSccU-XNbZZsL6eCByNTSsGGs_U1Z1jGeSeVaC_1Icc3rrlnbA/viewform)

**Comment by Arsollo** [comment]
Perfect, survey analysis is complete!
